services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SqlServer
    restart: always
    environment:
      SA_PASSWORD: "170421sqSE@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 170421sqSE@ -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s  

volumes:
  sql_data: